server:
  port: 8088
spring:
  application:
    name: xc-service-freemarker-test
  data:
    mongodb:
      uri:  mongodb://localhost:27017
      database: xc_cms
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
